Repository GangwonHyuIl/GangwonHyuIl, pull requests merged in 2024-08, with the labels that each got.

#28 Feat: 홈화면 바텀네비게이션 프레임 생성
  .idea/deploymentTargetSelector.xml
  .idea/other.xml
  .idea/vcs.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/gangwonhyuil/gangwonhyuil/presentation/AiFragment.kt
  app/src/main/java/com/gangwonhyuil/gangwonhyuil/presentation/CommunityFragment.kt
  app/src/main/java/com/gangwonhyuil/gangwonhyuil/presentation/HomeFragment.kt
  app/src/main/java/com/gangwonhyuil/gangwonhyuil/presentation/MainActivity.kt
  app/src/main/java/com/gangwonhyuil/gangwonhyuil/presentation/OnBodingActivity.kt
  app/src/main/java/com/gangwonhyuil/gangwonhyuil/presentation/ProfileFragment.kt
  app/src/main/res/drawable/ic_dashboard_black_24dp.xml
  app/src/main/res/drawable/ic_home_black_24dp.xml
  app/src/main/res/drawable/ic_notifications_black_24dp.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_on_boding.xml
  app/src/main/res/layout/fragment_ai.xml
  app/src/main/res/layout/fragment_community.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: feature

#29 Feat: 홈화면 바텀네비게이션 프레임 생성 #28 + 추가 수정
  .idea/deploymentTargetSelector.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/gangwonhyuil/gangwonhyuil/presentation/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
Labels: feature

#31 커뮤니티 화면 레이아웃 xml 작성 - 커뮤니티 화면, 글 상세 화면, 글 작성 화면, 장소 추가 화면
  .github/pull_request_template.md
  .idea/other.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/gangwonhyuil/gangwonhyuil/ui/community/addPlace/AddPlaceActivity.kt
  app/src/main/java/com/gangwonhyuil/gangwonhyuil/ui/community/addPost/AddPostActivity.kt
  app/src/main/java/com/gangwonhyuil/gangwonhyuil/ui/community/postDetail/PostDetailActivity.kt
  app/src/main/res/drawable/ic_accomodation_24.xml
  app/src/main/res/drawable/ic_add_24.xml
  app/src/main/res/drawable/ic_arrow_back_24.xml
  app/src/main/res/drawable/ic_cafe_24.xml
  app/src/main/res/drawable/ic_keyboard_arrow_down_24.xml
  app/src/main/res/drawable/ic_keyboard_arrow_up_24.xml
  app/src/main/res/drawable/ic_office_24.xml
  app/src/main/res/drawable/ic_restaurant_24.xml
  app/src/main/res/drawable/shape_border_radius_8.xml
  app/src/main/res/drawable/shape_circle.xml
  app/src/main/res/layout/activity_add_place.xml
  app/src/main/res/layout/activity_add_post.xml
  app/src/main/res/layout/activity_post_detail.xml
  app/src/main/res/layout/fragment_community.xml
  app/src/main/res/layout/rv_item_add_place_image.xml
  app/src/main/res/layout/rv_item_add_post_footer.xml
  app/src/main/res/layout/rv_item_add_post_header.xml
  app/src/main/res/layout/rv_item_add_post_place.xml
  app/src/main/res/layout/rv_item_app_place_image_header.xml
  app/src/main/res/layout/rv_item_community.xml
  app/src/main/res/layout/rv_item_post_detail_comment.xml
  app/src/main/res/layout/rv_item_post_detail_header.xml
  app/src/main/res/layout/rv_item_post_detail_place.xml
  app/src/main/res/layout/spinner_item_place_category.xml
  app/src/main/res/layout/vp_item_place_detail_image.xml
  app/src/main/res/menu/add_place_top_app_bar.xml
  app/src/main/res/menu/add_post_top_app_bar.xml
  app/src/main/res/menu/community_top_app_bar.xml
  app/src/main/res/menu/post_detail_top_app_bar.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/place_category.xml
Labels: feature, settings

#32 PR 자동화 github action 추가
  .github/workflows/build.yml
  app/src/main/res/layout/activity_add_place.xml
  app/src/main/res/layout/activity_add_post.xml
  app/src/main/res/values/place_category.xml
Labels: settings

#33 BaseFragment 추가 / 홈 화면에 스피너 작성
  app/build.gradle.kts
  app/src/main/java/com/gangwonhyuil/gangwonhyuil/ui/home/HomeFragment.kt
  app/src/main/java/com/gangwonhyuil/gangwonhyuil/util/base/BaseFragment.kt
  app/src/main/res/drawable/custom_spinner_background.xml
  app/src/main/res/layout/custom_spinner_item.xml
  app/src/main/res/layout/fragment_home.xml
  gradle/libs.versions.toml
Labels: feature, settings

#34 커뮤니티 홈 화면 레이아웃과 Fragment 코드 연결, BaseViewModel 추가, Hilt & Timber 추가
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/gangwonhyuil/gangwonhyuil/ui/BaseViewModel.kt
  app/src/main/java/com/gangwonhyuil/gangwonhyuil/ui/MainActivity.kt
  app/src/main/java/com/gangwonhyuil/gangwonhyuil/ui/MyApplication.kt
  app/src/main/java/com/gangwonhyuil/gangwonhyuil/ui/community/CommunityFragment.kt
  app/src/main/java/com/gangwonhyuil/gangwonhyuil/ui/community/entity/PostEntity.kt
  app/src/main/java/com/gangwonhyuil/gangwonhyuil/ui/community/screen/addPlace/AddPlaceActivity.kt
  app/src/main/java/com/gangwonhyuil/gangwonhyuil/ui/community/screen/addPost/AddPostActivity.kt
  app/src/main/java/com/gangwonhyuil/gangwonhyuil/ui/community/screen/community/CommunityFragment.kt
  app/src/main/java/com/gangwonhyuil/gangwonhyuil/ui/community/screen/community/CommunityViewModel.kt
  app/src/main/java/com/gangwonhyuil/gangwonhyuil/ui/community/screen/community/PlaceItemAdapter.kt
  app/src/main/java/com/gangwonhyuil/gangwonhyuil/ui/community/screen/community/PostItem.kt
  app/src/main/java/com/gangwonhyuil/gangwonhyuil/ui/community/screen/postDetail/PostDetailActivity.kt
  app/src/main/java/com/gangwonhyuil/gangwonhyuil/ui/community/useCase/GetPostsUseCase.kt
  app/src/main/java/com/gangwonhyuil/gangwonhyuil/util/base/BaseFragment.kt
  app/src/main/res/layout/activity_add_place.xml
  app/src/main/res/layout/activity_add_post.xml
  app/src/main/res/layout/activity_post_detail.xml
  app/src/main/res/layout/fragment_community.xml
  app/src/main/res/layout/rv_item_community.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/place_category.xml
  build.gradle.kts
  gradle/libs.versions.toml
Labels: feature

#35 BaseAdapter 작성, Spinner 추가, HomeFragment의 탭레이아웃의 뷰페이저 연결
  app/src/main/java/com/gangwonhyuil/gangwonhyuil/ui/home/HomeFragment.kt
  app/src/main/java/com/gangwonhyuil/gangwonhyuil/ui/home/HomePagerAdapter.kt
  app/src/main/java/com/gangwonhyuil/gangwonhyuil/ui/home/HomeViewModel.kt
  app/src/main/java/com/gangwonhyuil/gangwonhyuil/ui/home/office/OfficeAdapter.kt
  app/src/main/java/com/gangwonhyuil/gangwonhyuil/ui/home/office/OfficeInfoFragment.kt
  app/src/main/java/com/gangwonhyuil/gangwonhyuil/ui/home/office/OfficeItem.kt
  app/src/main/java/com/gangwonhyuil/gangwonhyuil/ui/home/office/OfficeViewModel.kt
  app/src/main/java/com/gangwonhyuil/gangwonhyuil/util/base/BaseAdapter.kt
  app/src/main/java/com/gangwonhyuil/gangwonhyuil/util/base/Eigenvalue.kt
  app/src/main/res/drawable/ic_arrow_backward_24.xml
  app/src/main/res/drawable/ic_arrow_left_24.xml
  app/src/main/res/drawable/ic_arrow_right_24.xml
  app/src/main/res/drawable/ic_chat_24.xml
  app/src/main/res/drawable/ic_star_rating_24.xml
  app/src/main/res/drawable/outline_chat_24.xml
  app/src/main/res/layout/activity_add_place.xml
  app/src/main/res/layout/activity_add_post.xml
  app/src/main/res/layout/activity_post_detail.xml
  app/src/main/res/layout/fragment_office_info.xml
  app/src/main/res/layout/rv_item_office.xml
Labels: feature

#36 BaseActivity 추가
  .idea/kotlinc.xml
  app/src/main/java/com/gangwonhyuil/gangwonhyuil/ui/community/screen/community/CommunityViewModel.kt
  app/src/main/java/com/gangwonhyuil/gangwonhyuil/ui/community/screen/postDetail/PostDetailActivity.kt
  app/src/main/java/com/gangwonhyuil/gangwonhyuil/util/base/BaseActivity.kt
  app/src/main/java/com/gangwonhyuil/gangwonhyuil/util/base/BaseFragment.kt
  app/src/main/java/com/gangwonhyuil/gangwonhyuil/util/base/BaseViewModel.kt
Labels: settings
